# NumPy pod dane: tablice, maski i proste statystyki

## Cele
- zamiana list Pythona na tablice NumPy
- czytanie podstawowych informacji o tablicy: shape, ndim, dtype
- operacje element-po-elemencie
- indeksowanie i slicing w 1D i 2D
- filtrowanie danych maską logiczną
- liczenie prostych statystyk: suma, średnia, min, max
- pierwsze użycie axis i reshape

## 0. Rozgrzewka (2 min)
Uruchom komórkę. Jeśli zobaczysz ✅, jesteś gotowy/a.

In [1]:
import numpy as np

print("NumPy start ✅")

NumPy start ✅


## Mała funkcja pomocnicza
Będziemy jej używać, żeby przeglądać zawartość tablicy i jej właściwości

In [2]:
def array_info(array: np.ndarray) -> None:
    print(f"Array:\n{array}")
    print(f"Shape: {array.shape}")
    print(f"Liczba wymiarów (ndim): {array.ndim}")
    print(f"Typ danych (dtype): {array.dtype}")

## 1. Z listy Pythona do tablicy NumPy

**Wskazówka:** `np.array(...)` zamienia listę na tablicę NumPy.

In [3]:
nums_list = [1, 2, 3, 4, 5]      # Zwykła lista Pythona.
nums = np.array(nums_list)       # Zamieniamy listę na tablicę NumPy.

array_info(nums)

Array:
[1 2 3 4 5]
Shape: (5,)
Liczba wymiarów (ndim): 1
Typ danych (dtype): int64


In [4]:
try:
    assert isinstance(nums, np.ndarray)
    assert nums.shape == (5,)
    assert nums.ndim == 1
    assert np.array_equal(nums, np.array([1, 2, 3, 4, 5]))
    print("OK ✅")
except Exception as e:
    print("Błąd:", e)

OK ✅


## 2. Tworzenie tablic

### Najczęstsze sposoby:
- `np.array(...)` – z listy
- `np.arange(...)` – zakres liczb
- `np.zeros(...)` – same zera
- `np.ones(...)` – same jedynki

In [5]:
a = np.arange(0, 10, 2)                # Liczby: 0, 2, 4, 6, 8
zeros = np.zeros((2, 3), dtype=int)   # Tablica 2x3 wypełniona zerami
ones = np.ones((2, 2), dtype=int)     # Tablica 2x2 wypełniona jedynkami

print("a:")
array_info(a)

print("\nzeros:")
array_info(zeros)

print("\nones:")
array_info(ones)

a:
Array:
[0 2 4 6 8]
Shape: (5,)
Liczba wymiarów (ndim): 1
Typ danych (dtype): int64

zeros:
Array:
[[0 0 0]
 [0 0 0]]
Shape: (2, 3)
Liczba wymiarów (ndim): 2
Typ danych (dtype): int64

ones:
Array:
[[1 1]
 [1 1]]
Shape: (2, 2)
Liczba wymiarów (ndim): 2
Typ danych (dtype): int64


In [6]:
try:
    assert np.array_equal(a, np.array([0, 2, 4, 6, 8]))
    assert zeros.shape == (2, 3)
    assert ones.shape == (2, 2)
    assert np.array_equal(zeros, np.array([[0, 0, 0], [0, 0, 0]]))
    assert np.array_equal(ones, np.array([[1, 1], [1, 1]]))
    print("OK ✅")
except Exception as e:
    print("Błąd:", e)

OK ✅


## 3. Operacje element-po-elemencie

W NumPy można liczyć na całych tablicach naraz.

**Wskazówka:** To nie jest „jedna liczba plus druga liczba”, tylko działanie na każdym elemencie osobno.

In [7]:
x = np.array([1, 2, 3, 4])         # Pierwsza tablica.
y = np.array([10, 20, 30, 40])     # Druga tablica o tym samym kształcie.

sum_xy = x + y                     # Dodawanie element-po-elemencie.
diff_xy = y - x                    # Odejmowanie element-po-elemencie.
mul_xy = x * y                     # Mnożenie element-po-elemencie.
pow_x2 = x ** 2                    # Każdy element x podnosimy do kwadratu.

print("x:", x)
print("y:", y)
print("x + y:", sum_xy)
print("y - x:", diff_xy)
print("x * y:", mul_xy)
print("x ** 2:", pow_x2)

x: [1 2 3 4]
y: [10 20 30 40]
x + y: [11 22 33 44]
y - x: [ 9 18 27 36]
x * y: [ 10  40  90 160]
x ** 2: [ 1  4  9 16]


In [8]:
try:
    assert np.array_equal(sum_xy, np.array([11, 22, 33, 44]))
    assert np.array_equal(diff_xy, np.array([9, 18, 27, 36]))
    assert np.array_equal(mul_xy, np.array([10, 40, 90, 160]))
    assert np.array_equal(pow_x2, np.array([1, 4, 9, 16]))
    print("OK ✅")
except Exception as e:
    print("Błąd:", e)

OK ✅


## 4. Tablica 2D: indeksowanie i slicing

To będzie nasza mała „tabela ocen”.
- wiersz = jeden student
- kolumna = jeden przedmiot

In [9]:
scores = np.array([
    [4, 5, 3],
    [5, 5, 4],
    [3, 4, 2],
    [2, 3, 3]
])

print("Oceny:")
print(scores)

Oceny:
[[4 5 3]
 [5 5 4]
 [3 4 2]
 [2 3 3]]


In [10]:
first_row = scores[0]        # Pierwszy wiersz.
first_col = scores[:, 0]     # Pierwsza kolumna.
element = scores[2, 1]       # Wiersz 3, kolumna 2 (liczymy od 0).
last_two_rows = scores[-2:]  # Dwa ostatnie wiersze.

print("Pierwszy wiersz:", first_row)
print("Pierwsza kolumna:", first_col)
print("Element [2, 1]:", element)
print("Dwa ostatnie wiersze:\n", last_two_rows)

Pierwszy wiersz: [4 5 3]
Pierwsza kolumna: [4 5 3 2]
Element [2, 1]: 4
Dwa ostatnie wiersze:
 [[3 4 2]
 [2 3 3]]


In [11]:
try:
    assert np.array_equal(first_row, np.array([4, 5, 3]))
    assert np.array_equal(first_col, np.array([4, 5, 3, 2]))
    assert element == 4
    assert np.array_equal(last_two_rows, np.array([[3, 4, 2], [2, 3, 3]]))
    print("OK ✅")
except Exception as e:
    print("Błąd:", e)

OK ✅


## 5. Proste statystyki i `axis`

### Intuicja:
- `axis=0` → liczymy „po wierszach”, dostajemy wynik dla kolumn
- `axis=1` → liczymy „po kolumnach”, dostajemy wynik dla wierszy

In [21]:
mean_all = scores.mean()           # Średnia ze wszystkich ocen.
sum_all = scores.sum()             # Suma wszystkich ocen.
min_score = scores.min()           # Najmniejsza ocena.
max_score = scores.max()           # Największa ocena.

mean_per_student = scores.mean(axis=1)   # Średnia dla każdego wiersza = każdego studenta.
mean_per_subject = scores.mean(axis=0)   # Średnia dla każdej kolumny = każdego przedmiotu.

score_range = max_score - min_score      # Rozstęp: max - min.

print("Średnia wszystkich ocen:", mean_all)
print("Suma wszystkich ocen:", sum_all)
print("Min:", min_score)
print("Max:", max_score)
print("Średnia per student:", mean_per_student)
print("Średnia per przedmiot:", mean_per_subject)
print("Rozstęp:", score_range)

Średnia wszystkich ocen: 3.5833333333333335
Suma wszystkich ocen: 43
Min: 2
Max: 5
Średnia per student: [4.         4.66666667 3.         2.66666667]
Średnia per przedmiot: [3.5  4.25 3.  ]
Rozstęp: 3


## 6. Maski logiczne: wybieramy tylko te dane, które spełniają warunek

**Wskazówka:** maska to tablica wartości `True` / `False`.

In [22]:
mask_ge4 = scores >= 4          # Sprawdzamy, które oceny są >= 4.
good_scores = scores[mask_ge4]  # Wyciągamy tylko te oceny.

print("Maska ocen >= 4:\n", mask_ge4)
print("Oceny >= 4:", good_scores)

Maska ocen >= 4:
 [[ True  True False]
 [ True  True  True]
 [False  True False]
 [False False False]]
Oceny >= 4: [4 5 5 5 4 4]


In [23]:
try:
    assert np.array_equal(
        mask_ge4,
        np.array([
            [ True,  True, False],
            [ True,  True,  True],
            [False,  True, False],
            [False, False, False]
        ])
    )
    assert np.array_equal(good_scores, np.array([4, 5, 5, 5, 4, 4]))
    print("OK ✅")
except Exception as e:
    print("Błąd:", e)

OK ✅


## 7. Maska + druga tablica: wybór konkretnych studentów

To jest bardzo ważny wzorzec pod analizę danych.

In [24]:
names = np.array(["Ala", "Ola", "Jan", "Piotr"])   # Imiona studentów.
student_means = scores.mean(axis=1)                # Średnia dla każdego studenta.
good_students_mask = student_means >= 4            # Którzy mają średnią co najmniej 4?
good_students = names[good_students_mask]          # Wybieramy ich imiona.

print("Średnie studentów:", student_means)
print("Maska dobrych studentów:", good_students_mask)
print("Studenci ze średnią >= 4:", good_students)

Średnie studentów: [4.         4.66666667 3.         2.66666667]
Maska dobrych studentów: [ True  True False False]
Studenci ze średnią >= 4: ['Ala' 'Ola']


In [25]:
try:
    assert np.allclose(student_means, np.array([4.0, 14/3, 3.0, 8/3]))
    assert np.array_equal(good_students_mask, np.array([True, True, False, False]))
    assert np.array_equal(good_students, np.array(["Ala", "Ola"]))
    print("OK ✅")
except Exception as e:
    print("Błąd:", e)

OK ✅


## 8. Zmiana kształtu: `reshape`

**Wskazówka:** Liczba elementów musi się zgadzać.
Na przykład 12 elementów można ułożyć jako:
- 3x4
- 2x6
- 6x2
- 1x12

In [26]:
flat = np.arange(1, 13)      # Liczby od 1 do 12.
table = flat.reshape(3, 4)   # 3 wiersze, 4 kolumny.
col = flat.reshape(-1, 1)    # NumPy samo policzy liczbę wierszy.

print("flat:", flat)
print("table:\n", table)
print("col:\n", col)
print("Shape table:", table.shape)
print("Shape col:", col.shape)

flat: [ 1  2  3  4  5  6  7  8  9 10 11 12]
table:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
col:
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
Shape table: (3, 4)
Shape col: (12, 1)


In [27]:
try:
    assert flat.shape == (12,)
    assert table.shape == (3, 4)
    assert col.shape == (12, 1)
    assert np.array_equal(table[0], np.array([1, 2, 3, 4]))
    print("OK ✅")
except Exception as e:
    print("Błąd:", e)


OK ✅
